DROP TABLE IF EXISTS `HELLOWORLD`;

CREATE TABLE `HELLOWORLD`(
    `id` INT(10)  AUTO_INCREMENT,
    `helloDifLeng` VARCHAR(30) NOT NULL,
    `lang` VARCHAR(15) NOT NULL,
    PRIMARY KEY(`id`)
    );
